name: "Helm Kubeconform (with schema support)"
description: "Generate manifests with `helm template` and run `kubeconform` on the results"
author: "Shiv Jha-Mathur"
inputs:
  strict:
    description: "Whether to enable strict mode"
    default: "true"
  additionalSchemaPaths:
    description: "Newline-separated list of paths to look for schemas under, including filename template"
    default: ""
  chartsDirectory:
    description: "Directory to search for chart directories under"
    default: "charts"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    KUBECONFORM_STRICT: "${{ inputs.strict }}"
    ADDITIONAL_SCHEMA_PATHS: "${{ inputs.additionalSchemaPaths }}"
    CHARTS_DIRECTORY: "${{ inputs.chartsDirectory }}"
    HELM_UPDATE_DEPENDENCIES: "true"
  args: []
